name: 'Terraform Plan'
on:
    pull_request:
        branches:
            - main

env:
    TF_ACCESS_KEY_ID: ${{ secrets.TF_ACCESS_KEY_ID }}
    TF_SECRET_ACCESS_KEY: ${{ secrets.TF_SECRET_ACCESS_KEY }}

jobs:
    terraform:
        name: 'VPC creation'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ env.TF_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ env.TF_SECRET_ACCESS_KEY }}
                aws-region: 'us-east-1'
            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.7
            - name : Terraform validation
              run: |
                pushd terraform/vpc
                terraform init
                terraform plan 
            - name : Terraform creation
              run: |                
                terraform apply -auto-approve
                popd
            - name: Commit Terraform Changes
              run: |
                git config --global user.name 'GitHub Actions'
                git config --global user.email 'facuassain@gmail.com'
                git commit -am "Valid Terraform plan"
                git push